### ISSUE TITLE
Failed to execute script docker-compose

### ISSUE THREAD

**Issue by daniel-dia** [p1c2u/vscode-docker-compose#21]
I installed Docker extension and I'm getting the fallowing error:

> Failed to exeute script docker-compose

I working on Windows 10 and VS Code 1.28.2 (user setup)

I have Docker and Docker Compose installed on my machine.

I Also have Docker extension enabled on VS Code.

Also searched for any error output but i didnt found anything

**Comment by p1c2u** [comment]
@daniel-dia 
1. Do you have docker-compose command in PATH? Open command prompt with `cmd` and execute `docker-compose -v`
2. Do you have `docker-compose.yml` file in workspace? Open command prompt with `cmd`, go to your workspace directory and execute `docker-compose ps`

**Comment by daniel-dia** [comment]
yes, all conditions satisfied.

![image](https://user-images.githubusercontent.com/2263037/48353040-8ca53700-e675-11e8-825a-7b74b3bc4302.png)

**Comment by p1c2u** [comment]
@daniel-dia hard to say what's the reason. I will add more error info  to next version.

**Comment by daniel-dia** [comment]
I Was able to find a little more detailed error report on "VS Developer Tools"

  ```

console.ts:134 [Extension Host] rejected promise not handled within 1 second
t.log @ console.ts:134
t._logExtensionHostMessage @ extensionHost.ts:437
(anonymous) @ extensionHost.ts:244
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180



ERR Cannot read property 'service' of undefined: TypeError: Cannot read property 'service' of undefined
	at DockerComposeProvider.<anonymous> (C:\Users\Daniel\.vscode\extensions\p1c2u.docker-compose-0.3.0\out\explorers\providers.js:119:38)
	at Generator.next (<anonymous>)
	at C:\Users\Daniel\.vscode\extensions\p1c2u.docker-compose-0.3.0\out\explorers\providers.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\Daniel\.vscode\extensions\p1c2u.docker-compose-0.3.0\out\explorers\providers.js:3:12)
	at DockerComposeProvider.upService (C:\Users\Daniel\.vscode\extensions\p1c2u.docker-compose-0.3.0\out\explorers\providers.js:118:16)
	at vscode.commands.registerCommand (C:\Users\Daniel\.vscode\extensions\p1c2u.docker-compose-0.3.0\out\extension.js:45:18)
	at e._executeContributedCommand (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:460:160)
	at e.$executeContributedCommand (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:460:648)
	at t._doInvokeHandler (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:609:757)
	at t._invokeHandler (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:609:423)
	at t._receiveRequest (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:608:15)
	at t._receiveOneMessage (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:606:957)
	at c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:604:773
	at c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:103:886
	at e.fire (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:105:344)
	at a (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:156:881)
	at Socket._socketDataListener (c:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:157:95)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

**Comment by p1c2u** [comment]
@daniel-dia Look at first line after `docker-compose ps` command. it's because you have the following error `O sistema não pode encontrar o caminho especificado`. It's Windows specific error.
